// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ArtifactDependencies artifact dependencies
// swagger:model artifact-dependencies
type ArtifactDependencies struct {

	// artifact dependency
	ArtifactDependency []*ArtifactDependency `json:"artifact-dependency"`

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// replace
	Replace string `json:"replace,omitempty" xml:"replace"`
}

// Validate validates this artifact dependencies
func (m *ArtifactDependencies) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateArtifactDependency(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ArtifactDependencies) validateArtifactDependency(formats strfmt.Registry) error {

	if swag.IsZero(m.ArtifactDependency) { // not required
		return nil
	}

	for i := 0; i < len(m.ArtifactDependency); i++ {
		if swag.IsZero(m.ArtifactDependency[i]) { // not required
			continue
		}

		if m.ArtifactDependency[i] != nil {
			if err := m.ArtifactDependency[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("artifact-dependency" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ArtifactDependencies) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArtifactDependencies) UnmarshalBinary(b []byte) error {
	var res ArtifactDependencies
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
