// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// IssuesUsages issues usages
// swagger:model issuesUsages
type IssuesUsages struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// href
	Href string `json:"href,omitempty" xml:"href"`

	// issue usage
	IssueUsage []*IssueUsage `json:"issueUsage"`
}

// Validate validates this issues usages
func (m *IssuesUsages) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIssueUsage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IssuesUsages) validateIssueUsage(formats strfmt.Registry) error {

	if swag.IsZero(m.IssueUsage) { // not required
		return nil
	}

	for i := 0; i < len(m.IssueUsage); i++ {
		if swag.IsZero(m.IssueUsage[i]) { // not required
			continue
		}

		if m.IssueUsage[i] != nil {
			if err := m.IssueUsage[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("issueUsage" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IssuesUsages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IssuesUsages) UnmarshalBinary(b []byte) error {
	var res IssuesUsages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
