// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Plugins plugins
// swagger:model plugins
type Plugins struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// plugin
	Plugin []*Plugin `json:"plugin"`
}

// Validate validates this plugins
func (m *Plugins) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePlugin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Plugins) validatePlugin(formats strfmt.Registry) error {

	if swag.IsZero(m.Plugin) { // not required
		return nil
	}

	for i := 0; i < len(m.Plugin); i++ {
		if swag.IsZero(m.Plugin[i]) { // not required
			continue
		}

		if m.Plugin[i] != nil {
			if err := m.Plugin[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("plugin" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Plugins) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Plugins) UnmarshalBinary(b []byte) error {
	var res Plugins
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
