// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProblemOccurrences problem occurrences
// swagger:model problemOccurrences
type ProblemOccurrences struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// default
	Default *bool `json:"default,omitempty"`

	// failed
	Failed int32 `json:"failed,omitempty" xml:"failed"`

	// href
	Href string `json:"href,omitempty" xml:"href"`

	// ignored
	Ignored int32 `json:"ignored,omitempty" xml:"ignored"`

	// muted
	Muted int32 `json:"muted,omitempty" xml:"muted"`

	// new failed
	NewFailed int32 `json:"newFailed,omitempty" xml:"newFailed"`

	// next href
	NextHref string `json:"nextHref,omitempty" xml:"nextHref"`

	// passed
	Passed int32 `json:"passed,omitempty" xml:"passed"`

	// prev href
	PrevHref string `json:"prevHref,omitempty" xml:"prevHref"`

	// problem occurrence
	ProblemOccurrence []*ProblemOccurrence `json:"problemOccurrence"`
}

// Validate validates this problem occurrences
func (m *ProblemOccurrences) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProblemOccurrence(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProblemOccurrences) validateProblemOccurrence(formats strfmt.Registry) error {

	if swag.IsZero(m.ProblemOccurrence) { // not required
		return nil
	}

	for i := 0; i < len(m.ProblemOccurrence); i++ {
		if swag.IsZero(m.ProblemOccurrence[i]) { // not required
			continue
		}

		if m.ProblemOccurrence[i] != nil {
			if err := m.ProblemOccurrence[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("problemOccurrence" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProblemOccurrences) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProblemOccurrences) UnmarshalBinary(b []byte) error {
	var res ProblemOccurrences
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
