// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ProjectFeatures project features
// swagger:model projectFeatures
type ProjectFeatures struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// href
	Href string `json:"href,omitempty" xml:"href"`

	// project feature
	ProjectFeature []*ProjectFeature `json:"projectFeature"`
}

// Validate validates this project features
func (m *ProjectFeatures) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProjectFeature(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ProjectFeatures) validateProjectFeature(formats strfmt.Registry) error {

	if swag.IsZero(m.ProjectFeature) { // not required
		return nil
	}

	for i := 0; i < len(m.ProjectFeature); i++ {
		if swag.IsZero(m.ProjectFeature[i]) { // not required
			continue
		}

		if m.ProjectFeature[i] != nil {
			if err := m.ProjectFeature[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("projectFeature" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ProjectFeatures) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectFeatures) UnmarshalBinary(b []byte) error {
	var res ProjectFeatures
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
