// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VcsRootInstances vcs root instances
// swagger:model vcs-root-instances
type VcsRootInstances struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// href
	Href string `json:"href,omitempty" xml:"href"`

	// next href
	NextHref string `json:"nextHref,omitempty" xml:"nextHref"`

	// prev href
	PrevHref string `json:"prevHref,omitempty" xml:"prevHref"`

	// vcs root instance
	VcsRootInstance []*VcsRootInstance `json:"vcs-root-instance"`
}

// Validate validates this vcs root instances
func (m *VcsRootInstances) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVcsRootInstance(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VcsRootInstances) validateVcsRootInstance(formats strfmt.Registry) error {

	if swag.IsZero(m.VcsRootInstance) { // not required
		return nil
	}

	for i := 0; i < len(m.VcsRootInstance); i++ {
		if swag.IsZero(m.VcsRootInstance[i]) { // not required
			continue
		}

		if m.VcsRootInstance[i] != nil {
			if err := m.VcsRootInstance[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vcs-root-instance" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *VcsRootInstances) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VcsRootInstances) UnmarshalBinary(b []byte) error {
	var res VcsRootInstances
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
