// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VcsRootEntries vcs root entries
// swagger:model vcs-root-entries
type VcsRootEntries struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// vcs root entry
	VcsRootEntry []*VcsRootEntry `json:"vcs-root-entry"`
}

// Validate validates this vcs root entries
func (m *VcsRootEntries) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVcsRootEntry(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VcsRootEntries) validateVcsRootEntry(formats strfmt.Registry) error {

	if swag.IsZero(m.VcsRootEntry) { // not required
		return nil
	}

	for i := 0; i < len(m.VcsRootEntry); i++ {
		if swag.IsZero(m.VcsRootEntry[i]) { // not required
			continue
		}

		if m.VcsRootEntry[i] != nil {
			if err := m.VcsRootEntry[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vcs-root-entry" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *VcsRootEntries) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VcsRootEntries) UnmarshalBinary(b []byte) error {
	var res VcsRootEntries
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
