// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// VcsRoots vcs roots
// swagger:model vcs-roots
type VcsRoots struct {

	// count
	Count int32 `json:"count,omitempty" xml:"count"`

	// href
	Href string `json:"href,omitempty" xml:"href"`

	// next href
	NextHref string `json:"nextHref,omitempty" xml:"nextHref"`

	// prev href
	PrevHref string `json:"prevHref,omitempty" xml:"prevHref"`

	// vcs root
	VcsRoot []*VcsRoot `json:"vcs-root"`
}

// Validate validates this vcs roots
func (m *VcsRoots) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVcsRoot(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VcsRoots) validateVcsRoot(formats strfmt.Registry) error {

	if swag.IsZero(m.VcsRoot) { // not required
		return nil
	}

	for i := 0; i < len(m.VcsRoot); i++ {
		if swag.IsZero(m.VcsRoot[i]) { // not required
			continue
		}

		if m.VcsRoot[i] != nil {
			if err := m.VcsRoot[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("vcs-root" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *VcsRoots) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VcsRoots) UnmarshalBinary(b []byte) error {
	var res VcsRoots
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
